### ISSUE TITLE
Occassional segfault when handling AggregationInfos.

### ISSUE THREAD

**Issue by kayabaNerve** [Chia-Network/bls-signatures#52]
Line 258 of aggregationinfo.cpp segfaults with:

```
Program received signal SIGSEGV, Segmentation fault.
__memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:99
99	../sysdeps/x86_64/multiarch/memcpy-ssse3.S: No such file or directory.
(gdb) where
#0  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:99
#1  0x000055555556e88d in bls::AggregationInfo::InsertIntoTree(std::map<unsigned char*, bn_st (*) [1], bls::Util::BytesCompare<80ul>, std::allocator<std::pair<unsigned char* const, bn_st (*) [1]> > >&, bls::AggregationInfo const&) ()
#2  0x000055555556dcfd in bls::AggregationInfo::AggregationInfo(bls::AggregationInfo const&) ()
```

For some reason, mapEntry.first is 1 in some cases.

**Comment by kayabaNerve** [comment]
Changing the line above it from
```
uint8_t* messageCopy = new uint8_t[BLS::MESSAGE_HASH_LEN + PublicKey::PUBLIC_KEY_SIZE];
```
to
```
uint8_t* messageCopy = (uint8_t*) malloc(BLS::MESSAGE_HASH_LEN + PublicKey::PUBLIC_KEY_SIZE);
```
seems to fix the issue.

**Comment by kayabaNerve** [comment]
This fix worked for a while, but now trying to aggregate 'regular' AggregationInfos segfaults, despite all the tests working. Because of that, I can no longer say that the MergeInfos produced AIs were the issue in the first place.

This leaves me to guess at what part of my code is acting it up and why. Even if I gut threads out, it still segfaults.

**Comment by kayabaNerve** [comment]
The title change was because I created this issue when I had much less info. I had some theories which didn't help, so I purged them.

**Comment by kayabaNerve** [comment]
It was an issue with the GC I'm using. @mariano54 helped me solve the issue, despite it not being related to the library.
