### ISSUE TITLE
Python impl: `RecursionError` when trying to sign a message

### ISSUE THREAD

**Issue by mhchia** [Chia-Network/bls-signatures#63]
Commit: fb76bf5007c226e354ae8c0a699c80f70dadd7f5

I haven't looked into the cause. Just want to bring this up and see if anyone encounters this issue. Will really appreciate if there is any clue to the solution.

```python
>>> import keys
>>> p2 = keys.PrivateKey.from_bytes(int(5566).to_bytes(32, 'big'))
>>> m = b'\x32'*32
>>> p2.sign(m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/projects/bls/bls-signatures/python-impl/keys.py", line 145, in sign
    r = hash_to_point_Fq2(m).to_jacobian()
  File "~/projects/bls/bls-signatures/python-impl/ec.py", line 508, in hash_to_point_Fq2
    return hash_to_point_prehashed_Fq2(h, ec)
  File "~/projects/bls/bls-signatures/python-impl/ec.py", line 492, in hash_to_point_prehashed_Fq2
    P = sw_encode(t0, ec, Fq2) + sw_encode(t1, ec, Fq2)
  File "~/projects/bls/bls-signatures/python-impl/ec.py", line 456, in sw_encode
    ys = y_for_x(xs[index], ec, FE)
  File "~/projects/bls/bls-signatures/python-impl/ec.py", line 205, in y_for_x
    y = u.modsqrt()
  File "~/projects/bls/bls-signatures/python-impl/fields.py", line 404, in modsqrt
    gamma = pow(alpha, (self.Q - 1)//2)
  File "~/projects/bls/bls-signatures/python-impl/fields.py", line 77, in __pow__
    return (self * self) ** (other // 2) * self
  File "~/projects/bls/bls-signatures/python-impl/fields.py", line 75, in __pow__
    return (self * self) ** (other // 2)
  File "~/projects/bls/bls-signatures/python-impl/fields.py", line 77, in __pow__
    return (self * self) ** (other // 2) * self
...
  File "~/projects/bls/bls-signatures/python-impl/fields.py", line 41, in __mul__
    return Fq(self.Q, super().__mul__(other))
  File "~/projects/bls/bls-signatures/python-impl/fields.py", line 11, in __new__
    ret = super().__new__(cls, x % Q)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by nmarley** [comment]
Does your script work if you set a higher recursion limit? E.g.: if you put `setrecursionlimit(10**6)` above your code?

The pure-Python test script does the same:

https://github.com/Chia-Network/bls-signatures/blob/ef18752318704f0eac1de70eb3c541c70fa9279d/python-impl/tests.py#L16

**Comment by mariano54** [comment]
Pow is doing a (double and add) algorithm through recursion. Fields.py line 69. It can be changed to not be recursive, or just increment the recursion limit.

**Comment by mhchia** [comment]
Thanks for the prompt answer. A higher recursion limit works:) IMO it makes sense to switch to a non-recursive implementation in this case tho.

**Comment by mariano54** [comment]
Thanks for report! Not maintaining the pure python implementation too much, since it's there for reference. If you need to use the library, you should use the python bindings which wrap the c++ implementation!

**Comment by mhchia** [comment]
I totally understand. Thank you for explaining! I'm using the python bindings and it is really good. Just traced and played with the python-impl for easier understanding(since I didn't code in C++ for a long time 😂)
